### ISSUE TITLE
ongeldige class MenuEditorExtension

### ISSUE THREAD

**Issue by melcarthus** [bacbos/bolt-menu-editor#65] opened 2017-08-03 14:43 UTC
After installation of the extension 3.2.2 this error appears.
```
Extensie package bacboslab/menueditor heeft een ongeldige class 'Bolt\Extension\Bacboslab\Menueditor\MenueditorExtension' en is overgeslagen.

```
Extensions
Bolt 3.3.1
Translate 4.0.9.

Apache 2.4
PHP 7

**Comment by SahAssar** [comment] 2017-10-12 19:32
Sorry, that it has taken me so long to look at this, but I can't reproduce this, do you still see this happening?

If so is this via the GUI, cli or straight composer require?

**Comment by melcarthus** [comment] 2017-10-12 21:22
after installation via gui. but this was for an older version. will have to see if this is reproducible for me still.. ill get back to you soon

**Comment by SahAssar** [comment] 2018-07-29 16:59
Closing cause it can't be reproduced.

**Closed by SahAssar** 2018-07-29 16:59 UTC
