### ISSUE TITLE
No searchbox appears on Firefox

### ISSUE THREAD

**Issue by evertalbers** [bacbos/bolt-menu-editor#5] opened 2014-12-24 13:44 UTC
On both Windows and Mac, the 'search for an item to add' input field does not appear in Firefox34.

In Chrome and Safari (both OSX), all is well though. I have not tested other  browsers. 

Using Bolt 2.0.2 and Menueditor "2.0.0    Stable release for bolt 2.0"

**Comment by bacbos** [comment] 2015-01-05 14:49
Issues in firefox are fixed with the latest version of the menu editor (2.0.2).
I couldn't reproduce the strange behavior in Safari though, might have been linked to the same issue firefox was having. Let me know if the problem still persists.

Currently, there's an issue with the extensions library not updating, so you won't be able to install the latest menu editor version until this is resolved. Follow https://github.com/bolt/bolt/issues/2406 for updates on this.

**Closed by bacbos** 2015-01-05 14:49 UTC

**Comment by evertalbers** [comment] 2015-01-05 15:02
Thanks!
