### ISSUE TITLE
[BUG] No full working version and no labels Ver. 3.1.3 with Bolt 3.2.3

### ISSUE THREAD

**Issue by sbonardt** [bacbos/bolt-menu-editor#48] opened 2017-01-16 09:00 UTC
Hi,

I always use your module on my projects as it's great for the end users!
However, now I'm working with the latest Bolt and I do not get all options when I want to add a menu item. Also the labels for the extension are not "in place": I see for instance 'menueditor.menuitem' in the sidebar menu and menueditor.actions.add (see screenshot)

I've tried older v3 versions but they all do it. Any idea?
![screen shot 2017-01-16 at 09 56 16](https://cloud.githubusercontent.com/assets/5597447/21976528/96573118-dbd2-11e6-9e43-cf42d78e44a3.png)

**Comment by navelpluisje** [comment] 2017-01-17 19:47
Also mentioned in #35. Try clearing your cache. Should do the trick

**Comment by use** [comment] 2017-01-19 23:51
I'm having the same problem on 3.1.3 with Bolt 3.2.5

Clearing the cache didn't fix the problem.

**Comment by SahAssar** [comment] 2017-01-20 19:04
@use & @sbonardt: What are your locales in the main config?

**Comment by use** [comment] 2017-01-23 20:44
@SahAssar here is the locale line from my config.yml:

```
locale: en_GB
```

**Comment by navelpluisje** [comment] 2017-01-23 20:52
@use Just tried it and works ok for me.
@SahAssar , may it help to `Rebuild  Autoloader` in the `Extend` menu?

**Comment by use** [comment] 2017-01-23 21:21
@navelpluisje hm, that didn't work for me. Out of curiosity I just tried the menueditor extension on a 3.2.4 install, and saw the same problem (looks like the screenshot above).

**Comment by navelpluisje** [comment] 2017-01-23 22:00
Hmmm, weird. Had a local version of the extension running for development. After disabling this one and reinstalling the latest version I'm having the same issue.
After setting the locale to `nl_NL` the plugin gets translated to dutch, but after turning back to `en_GB` or `en` it all is messed up again. Also tried some german locales and all of them are working fine. To me it looks like Bolt does not get the right translation for the default language. Will take a closer look at it tomorrow.

**Comment by navelpluisje** [comment] 2017-01-24 20:32
@use I did some fiddling around and think the issue is caused by the translation cache. Can you try to delete the `trans`-folder within `/app/cache/`? That's where the translations go. Can you let me know if it works?

Cheers

**Comment by use** [comment] 2017-01-26 00:13
@navelpluisje Hm, odd - I manually deleted /app/cache/trans from disk, yet it didn't solve the issue for me.

**Comment by SahAssar** [comment] 2017-01-30 09:06
Fixed in #51 and added to the latest tagged release. We now default back to the english release if we fail to load the proper translations. To use another locale /app/cache/trans will have to be deleted until this is solved in bolt core.

**Closed by SahAssar** 2017-01-30 09:06 UTC
Labels: Bolt bug/issue
